# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'docker build -f Dockerfile -t terraform .'
  displayName: 'Docker Build'
  
- task: CmdLine@2
  inputs:
    script: 'docker images'
  displayName: 'Docker Images'

- task: CmdLine@2
  inputs:
    script: 'docker image rm terraform'
  displayName: 'Delete Image'

